/* ------------------------------------------------------------------------------------- */
/*                 LISTAS DE DATOS: PAISES Y MUNICIPIOS DE COLOMBIA                       */
/* ------------------------------------------------------------------------------------- */
/* Estas listas alimentan los campos desplegables (Select2) de País y Ciudad.            */

const PAISES = [
  "AFGANISTÁN", "ALBANIA", "ALEMANIA", "ANDORRA", "ANGOLA", "ANTIGUA Y BARBUDA",
  "ARABIA SAUDITA", "ARGELIA", "ARGENTINA", "ARMENIA", "AUSTRALIA", "AUSTRIA",
  "AZERBAIYÁN", "BAHAMAS", "BANGLADÉS", "BARBADOS", "BARÉIN", "BÉLGICA", "BELICE",
  "BENÍN", "BIELORRUSIA", "BIRMANIA (MYANMAR)", "BOLIVIA", "BOSNIA Y HERZEGOVINA",
  "BOTSUANA", "BRASIL", "BRUNÉI", "BULGARIA", "BURKINA FASO", "BURUNDI", "BUTÁN",
  "CABO VERDE", "CAMBOYA", "CAMERÚN", "CANADÁ", "CATAR", "CHAD", "CHILE", "CHINA",
  "CHIPRE", "CIUDAD DEL VATICANO", "COLOMBIA", "COMORAS", "COREA DEL NORTE",
  "COREA DEL SUR", "COSTA DE MARFIL", "COSTA RICA", "CROACIA", "CUBA", "DINAMARCA",
  "DOMINICA", "ECUADOR", "EGIPTO", "EL SALVADOR", "EMIRATOS ÁRABES UNIDOS", "ERITREA",
  "ESLOVAQUIA", "ESLOVENIA", "ESPAÑA", "ESTADOS UNIDOS", "ESTONIA", "ESUATINI",
  "ETIOPÍA", "FILIPINAS", "FINLANDIA", "FIYI", "FRANCIA", "GABÓN", "GAMBIA", "GEORGIA",
  "GHANA", "GRANADA", "GRECIA", "GUATEMALA", "GUINEA", "GUINEA-BISÁU",
  "GUINEA ECUATORIAL", "GUYANA", "HAITÍ", "HONDURAS", "HUNGRÍA", "INDIA", "INDONESIA",
  "IRAK", "IRÁN", "IRLANDA", "ISLANDIA", "ISLAS MARSHALL", "ISLAS SALOMÓN", "ISRAEL",
  "ITALIA", "JAMAICA", "JAPÓN", "JORDANIA", "KAZAJISTÁN", "KENIA", "KIRGUISTÁN",
  "KIRIBATI", "KUWAIT", "LAOS", "LESOTO", "LETONIA", "LÍBANO", "LIBERIA", "LIBIA",
  "LIECHTENSTEIN", "LITUANIA", "LUXEMBURGO", "MADAGASCAR", "MALASIA", "MALAUI",
  "MALDIVAS", "MALÍ", "MALTA", "MARRUECOS", "MAURICIO", "MAURITANIA", "MÉXICO",
  "MICRONESIA", "MOLDAVIA", "MÓNACO", "MONGOLIA", "MONTENEGRO", "MOZAMBIQUE",
  "NAMIBIA", "NAURU", "NEPAL", "NICARAGUA", "NÍGER", "NIGERIA", "NORUEGA",
  "NUEVA ZELANDA", "OMÁN", "PAÍSES BAJOS", "PAKISTÁN", "PALAOS", "PANAMÁ",
  "PAPÚA NUEVA GUINEA", "PARAGUAY", "PERÚ", "POLONIA", "PORTUGAL", "REINO UNIDO",
  "REPÚBLICA CENTROAFRICANA", "REPÚBLICA CHECA", "REPÚBLICA DEL CONGO",
  "REPÚBLICA DEMOCRÁTICA DEL CONGO", "REPÚBLICA DOMINICANA", "RUANDA", "RUMANÍA",
  "RUSIA", "SAMOA", "SAN CRISTÓBAL Y NIEVES", "SAN MARINO",
  "SAN VICENTE Y LAS GRANADINAS", "SANTA LUCÍA", "SANTO TOMÉ Y PRÍNCIPE", "SENEGAL",
  "SERBIA", "SEYCHELLES", "SIERRA LEONA", "SINGAPUR", "SIRIA", "SOMALIA", "SRI LANKA",
  "SUDÁFRICA", "SUDÁN", "SUDÁN DEL SUR", "SUECIA", "SUIZA", "SURINAM", "TAILANDIA",
  "TANZANIA", "TAYIKISTÁN", "TIMOR ORIENTAL", "TOGO", "TONGA", "TRINIDAD Y TOBAGO",
  "TÚNEZ", "TURKMENISTÁN", "TURQUÍA", "TUVALU", "UCRANIA", "UGANDA", "URUGUAY",
  "UZBEKISTÁN", "VANUATU", "VENEZUELA", "VIETNAM", "YEMEN", "YIBUTI", "ZAMBIA",
  "ZIMBABUE"
];

/* Municipios de Colombia (capitales departamentales y principales municipios). */
const CIUDADES_COLOMBIA = [
  "BOGOTÁ D.C.",
  // Amazonas
  "LETICIA", "PUERTO NARIÑO",
  // Antioquia
  "MEDELLÍN", "BELLO", "ITAGÜÍ", "ENVIGADO", "APARTADÓ", "TURBO", "RIONEGRO",
  "SABANETA", "COPACABANA", "LA ESTRELLA", "CALDAS", "GIRARDOTA", "BARBOSA",
  "CAUCASIA", "CAREPA", "CHIGORODÓ", "NECOCLÍ", "EL BAGRE", "SANTA FE DE ANTIOQUIA",
  "ANDES", "MARINILLA", "LA CEJA", "GUARNE", "PUERTO BERRÍO", "YARUMAL", "SEGOVIA",
  // Arauca
  "ARAUCA", "ARAUQUITA", "SARAVENA", "TAME", "FORTUL",
  // Atlántico
  "BARRANQUILLA", "SOLEDAD", "MALAMBO", "SABANALARGA", "PUERTO COLOMBIA",
  "GALAPA", "BARANOA", "SABANAGRANDE", "SANTO TOMÁS", "PALMAR DE VARELA",
  // Bolívar
  "CARTAGENA", "MAGANGUÉ", "TURBACO", "ARJONA", "EL CARMEN DE BOLÍVAR",
  "MOMPÓS", "MARÍA LA BAJA", "SAN JUAN NEPOMUCENO", "SAN PABLO", "MORALES",
  // Boyacá
  "TUNJA", "DUITAMA", "SOGAMOSO", "CHIQUINQUIRÁ", "PAIPA", "VILLA DE LEYVA",
  "PUERTO BOYACÁ", "MONIQUIRÁ", "GARAGOA", "SAMACÁ", "NOBSA", "TIBASOSA",
  // Caldas
  "MANIZALES", "LA DORADA", "CHINCHINÁ", "VILLAMARÍA", "RIOSUCIO", "ANSERMA",
  "SUPÍA", "AGUADAS", "MANZANARES", "SALAMINA",
  // Caquetá
  "FLORENCIA", "SAN VICENTE DEL CAGUÁN", "PUERTO RICO", "EL DONCELLO",
  "LA MONTAÑITA", "BELÉN DE LOS ANDAQUÍES",
  // Casanare
  "YOPAL", "AGUAZUL", "VILLANUEVA", "TAURAMENA", "MONTERREY", "PAZ DE ARIPORO",
  "MANÍ", "OROCUÉ",
  // Cauca
  "POPAYÁN", "SANTANDER DE QUILICHAO", "PUERTO TEJADA", "PATÍA (EL BORDO)",
  "GUAPI", "PIENDAMÓ", "MIRANDA", "CALOTO", "CORINTO", "SILVIA",
  // Cesar
  "VALLEDUPAR", "AGUACHICA", "BOSCONIA", "CODAZZI", "LA JAGUA DE IBIRICO",
  "CHIRIGUANÁ", "CURUMANÍ", "EL COPEY", "SAN ALBERTO", "PAILITAS",
  // Chocó
  "QUIBDÓ", "ISTMINA", "TADÓ", "CONDOTO", "ACANDÍ", "BAHÍA SOLANO", "NUQUÍ",
  // Córdoba
  "MONTERÍA", "LORICA", "CERETÉ", "SAHAGÚN", "MONTELÍBANO", "PLANETA RICA",
  "TIERRALTA", "CIÉNAGA DE ORO", "PUERTO LIBERTADOR", "AYAPEL", "CHINÚ",
  // Cundinamarca
  "SOACHA", "FACATATIVÁ", "ZIPAQUIRÁ", "CHÍA", "GIRARDOT", "FUSAGASUGÁ",
  "MOSQUERA", "MADRID", "FUNZA", "CAJICÁ", "SIBATÉ", "TOCANCIPÁ", "LA CALERA",
  "COTA", "CHOCONTÁ", "UBATÉ", "VILLETA", "SOPÓ", "TENJO", "GACHANCIPÁ", "ANAPOIMA",
  "LA MESA", "FÓMEQUE", "PACHO", "CÁQUEZA",
  // Guainía
  "INÍRIDA",
  // Guaviare
  "SAN JOSÉ DEL GUAVIARE", "EL RETORNO", "CALAMAR", "MIRAFLORES",
  // Huila
  "NEIVA", "PITALITO", "GARZÓN", "LA PLATA", "CAMPOALEGRE", "GIGANTE", "AIPE",
  "SAN AGUSTÍN", "PALERMO", "RIVERA",
  // La Guajira
  "RIOHACHA", "MAICAO", "URIBIA", "MANAURE", "SAN JUAN DEL CESAR", "FONSECA",
  "BARRANCAS", "VILLANUEVA (LA GUAJIRA)", "ALBANIA", "DIBULLA",
  // Magdalena
  "SANTA MARTA", "CIÉNAGA", "FUNDACIÓN", "EL BANCO", "ZONA BANANERA", "PLATO",
  "ARACATACA", "PIVIJAY", "SANTA ANA", "PUEBLOVIEJO",
  // Meta
  "VILLAVICENCIO", "ACACÍAS", "GRANADA", "PUERTO LÓPEZ", "CUMARAL",
  "SAN MARTÍN", "RESTREPO", "PUERTO GAITÁN", "GUAMAL", "CASTILLA LA NUEVA",
  // Nariño
  "PASTO", "TUMACO", "IPIALES", "TÚQUERRES", "LA UNIÓN", "SANDONÁ", "SAMANIEGO",
  "BARBACOAS", "LA CRUZ", "PUPIALES",
  // Norte de Santander
  "CÚCUTA", "OCAÑA", "PAMPLONA", "VILLA DEL ROSARIO", "LOS PATIOS", "TIBÚ",
  "EL ZULIA", "SARDINATA", "CHINÁCOTA", "ÁBREGO",
  // Putumayo
  "MOCOA", "PUERTO ASÍS", "ORITO", "VALLE DEL GUAMUEZ (LA HORMIGA)",
  "PUERTO CAICEDO", "VILLAGARZÓN", "SIBUNDOY",
  // Quindío
  "ARMENIA", "CALARCÁ", "MONTENEGRO", "LA TEBAIDA", "QUIMBAYA", "CIRCASIA",
  "FILANDIA", "SALENTO",
  // Risaralda
  "PEREIRA", "DOSQUEBRADAS", "SANTA ROSA DE CABAL", "LA VIRGINIA", "QUINCHÍA",
  "MARSELLA", "BELÉN DE UMBRÍA",
  // San Andrés y Providencia
  "SAN ANDRÉS", "PROVIDENCIA",
  // Santander
  "BUCARAMANGA", "FLORIDABLANCA", "GIRÓN", "PIEDECUESTA", "BARRANCABERMEJA",
  "SAN GIL", "SOCORRO", "MÁLAGA", "VÉLEZ", "BARBOSA (SANTANDER)", "LEBRIJA",
  "SABANA DE TORRES", "RIONEGRO (SANTANDER)",
  // Sucre
  "SINCELEJO", "COROZAL", "SAMPUÉS", "SAN MARCOS", "SAN ONOFRE", "TOLÚ",
  "SINCÉ", "MAJAGUAL", "OVEJAS",
  // Tolima
  "IBAGUÉ", "ESPINAL", "MELGAR", "HONDA", "LÍBANO", "CHAPARRAL", "MARIQUITA",
  "FRESNO", "GUAMO", "PURIFICACIÓN", "FLANDES", "LÉRIDA",
  // Valle del Cauca
  "CALI", "BUENAVENTURA", "PALMIRA", "TULUÁ", "CARTAGO", "BUGA", "JAMUNDÍ",
  "YUMBO", "CANDELARIA", "FLORIDA", "PRADERA", "SEVILLA", "ZARZAL", "ROLDANILLO",
  "EL CERRITO", "CAICEDONIA", "GUACARÍ", "LA UNIÓN (VALLE)",
  // Vaupés
  "MITÚ",
  // Vichada
  "PUERTO CARREÑO", "LA PRIMAVERA", "CUMARIBO"
];
